/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Velis | v1
 * OpenAPI spec version: 1.0.0
 */

export type Mode = (typeof Mode)[keyof typeof Mode];

export const Mode = {
  Manual: "Manual",
  Eco: "Eco",
  Scheduled: "Scheduled",
} as const;
