/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Velis | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Mode } from "./mode";

export interface SenorsInfo {
  on?: boolean;
  mode?: Mode;
  currentTemperature?: number;
  requiredTemperature?: number;
  processingTemperature?: number;
  antiLegionellaInProgress?: boolean;
  isHeating?: boolean;
  eco?: boolean;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  remainingTime?: string;
  availableShowers?: number;
}
