/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Velis | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { SenorsInfo } from "./";

export const fetchSensors = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SenorsInfo>> => {
  return axios.default.get(`/api/fetch-sensors`, options);
};

export const getFetchSensorsQueryKey = () => {
  return [`/api/fetch-sensors`] as const;
};

export const getFetchSensorsQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchSensors>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof fetchSensors>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFetchSensorsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchSensors>>> = ({
    signal,
  }) => fetchSensors({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchSensors>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchSensorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchSensors>>
>;
export type FetchSensorsQueryError = AxiosError<unknown>;

export function useFetchSensors<
  TData = Awaited<ReturnType<typeof fetchSensors>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchSensors>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSensors>>,
          TError,
          Awaited<ReturnType<typeof fetchSensors>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchSensors<
  TData = Awaited<ReturnType<typeof fetchSensors>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchSensors>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSensors>>,
          TError,
          Awaited<ReturnType<typeof fetchSensors>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchSensors<
  TData = Awaited<ReturnType<typeof fetchSensors>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchSensors>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFetchSensors<
  TData = Awaited<ReturnType<typeof fetchSensors>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof fetchSensors>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchSensorsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const setTemperature = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.default.post(`/api/temperature`, undefined, options);
};

export const getSetTemperatureMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setTemperature>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setTemperature>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["setTemperature"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setTemperature>>,
    void
  > = () => {
    return setTemperature(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetTemperatureMutationResult = NonNullable<
  Awaited<ReturnType<typeof setTemperature>>
>;

export type SetTemperatureMutationError = AxiosError<unknown>;

export const useSetTemperature = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setTemperature>>,
      TError,
      void,
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof setTemperature>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSetTemperatureMutationOptions(options), queryClient);
};
